### ISSUE TITLE
关于运行出错

### ISSUE THREAD

**Issue by XuErShuo** [XunshanMan/Object-oriented-SLAM#1]
你好，程序编译时出现几个警告，但还是编译通过了，运行演示命令./build/rgbd ./Example/param/TUM3.yaml ./Example/dataset/cabinet/，按下回车键后程序就退出，提示总线错误（核心已转储），是不是代码里的访问内存出错了？感谢！

**Comment by XunshanMan** [comment]
你好，
确实发现部分环境有出现报错的情况。
已经更新了一版，请尝试 git pull 编译测试。
感谢关注。

**Comment by heng94** [comment]
@XunshanMan 你好，我用git pull 更新到最新版了，还是出现按下回车键就崩溃的情况，

**Comment by XunshanMan** [comment]
> @XunshanMan 你好，我用git pull 更新到最新版了，还是出现按下回车键就崩溃的情况，

你好，能提供崩溃前后控制台输出的内容吗？谢谢

**Comment by heng94** [comment]
@XunshanMan 感谢回复。
输出如下：
- settings file: ./Example/param/TUM3.yaml
- dataset_path: ./Example/dataset/cabinet/
- strDetectionDir: ./Example/dataset/cabinet/bbox/
Load dataset from: ./Example/dataset/cabinet/
mmTimeStampToPose: 58
mvIdToDepthImagePath: 58
mvIdToGroundtruthTimeStamp: 58

EllipsoidSLAM Project 2019, Beihang University.
 Input Sensor: RGB-D 

Camera Parameters: 
- fx: 535.4
- fy: 539.2
- cx: 320.1
- cy: 247.6
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 30
- rows: 480
- cols: 640
- Scale: 5000

 * Open Symmetry Estimation. 

 * Open Single-Frame Ellipsoid Estimation. 

 * Open Groundplane Estimation

*****************************
Press [ENTER] to continue ... 
*****************************

Segmentation fault (core dumped)

**Comment by heng94** [comment]
@XunshanMan  
I have recompiled the whole project, and I can get some visualization, but there still are some errors.
The output is as follows:

- settings file: ./Example/param/TUM3.yaml
- dataset_path: ./Example/dataset/cabinet/
- strDetectionDir: ./Example/dataset/cabinet/bbox/
Load dataset from: ./Example/dataset/cabinet/
mmTimeStampToPose: 58
mvIdToDepthImagePath: 58
mvIdToGroundtruthTimeStamp: 58

EllipsoidSLAM Project 2019, Beihang University.
 Input Sensor: RGB-D 

Camera Parameters: 
- fx: 535.4
- fy: 539.2
- cx: 320.1
- cy: 247.6
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 30
- rows: 480
- cols: 640
- Scale: 5000

 * Open Symmetry Estimation. 

 * Open Single-Frame Ellipsoid Estimation. 

 * Open Groundplane Estimation

*****************************
Press [ENTER] to continue ... 
*****************************

--------> New Frame : 0 Timestamp: 1341841278.842700
[Frame.cpp] bboxMap : 
   0  175   24  560  397   28 0.42    0

 * Estimate Ground Plane Succeeds: -0.0342327 0.00459375   0.999436  -0.103871
 * Add supporting plane to Ellipsoid Extractor.
 * Set groundplane param to optimizer. 
 -- Optimization parameters : 
 [ Using Ground Plane: -0.0342327 0.00459375   0.999436  -0.103871 ] 
 * Gravity Prior : Open.
 * Scale_3dedge: 10000
 * Scale_GravityPrior: 100
 -- GRAPH INFORMATION : 
 * Object Num : 1
 * Vertices: 2
 * 2d Edges [Valid/Invalid] : 0 [0/0]
 * 3d Edges : 1
 * Gravity edges: 1


 -> 1/58
*****************************
Press [ENTER] to continue ... 
*****************************

--------> New Frame : 1 Timestamp: 1341841279.510700
[Frame.cpp] bboxMap : 
   0  201   40  542  426   28 0.32    0

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Thanks for your help~

**Comment by XuErShuo** [comment]
> @XunshanMan
> I have recompiled the whole project, and I can get some visualization, but there still are some errors.
> The output is as follows:
> 
> * settings file: ./Example/param/TUM3.yaml
> * dataset_path: ./Example/dataset/cabinet/
> * strDetectionDir: ./Example/dataset/cabinet/bbox/
>   Load dataset from: ./Example/dataset/cabinet/
>   mmTimeStampToPose: 58
>   mvIdToDepthImagePath: 58
>   mvIdToGroundtruthTimeStamp: 58
> 
> EllipsoidSLAM Project 2019, Beihang University.
> Input Sensor: RGB-D
> 
> Camera Parameters:
> 
> * fx: 535.4
> * fy: 539.2
> * cx: 320.1
> * cy: 247.6
> * k1: 0
> * k2: 0
> * p1: 0
> * p2: 0
> * fps: 30
> * rows: 480
> * cols: 640
> * Scale: 5000
> 
> * Open Symmetry Estimation.
> * Open Single-Frame Ellipsoid Estimation.
> * Open Groundplane Estimation
> 
> Press [ENTER] to continue ...
> 
> --------> New Frame : 0 Timestamp: 1341841278.842700
> [Frame.cpp] bboxMap :
> 0 175 24 560 397 28 0.42 0
> 
> * Estimate Ground Plane Succeeds: -0.0342327 0.00459375   0.999436  -0.103871
> * Add supporting plane to Ellipsoid Extractor.
> * Set groundplane param to optimizer.
>   -- Optimization parameters :
>   [ Using Ground Plane: -0.0342327 0.00459375   0.999436  -0.103871 ]
> * Gravity Prior : Open.
> * Scale_3dedge: 10000
> * Scale_GravityPrior: 100
>   -- GRAPH INFORMATION :
> * Object Num : 1
> * Vertices: 2
> * 2d Edges [Valid/Invalid] : 0 [0/0]
> * 3d Edges : 1
> * Gravity edges: 1
> 
> -> 1/58
> 
> Press [ENTER] to continue ...
> 
> --------> New Frame : 1 Timestamp: 1341841279.510700
> [Frame.cpp] bboxMap :
> 0 201 40 542 426 28 0.32 0
> 
> terminate called after throwing an instance of 'std::bad_alloc'
> what(): std::bad_alloc
> Aborted (core dumped)
> 
> Thanks for your help~

有可能电脑的内存不足，尝试增加交换分区swap试试

**Comment by Hao-HUST** [comment]
> @XunshanMan
> I have recompiled the whole project, and I can get some visualization, but there still are some errors.
> The output is as follows:
> 
> * settings file: ./Example/param/TUM3.yaml
> * dataset_path: ./Example/dataset/cabinet/
> * strDetectionDir: ./Example/dataset/cabinet/bbox/
>   Load dataset from: ./Example/dataset/cabinet/
>   mmTimeStampToPose: 58
>   mvIdToDepthImagePath: 58
>   mvIdToGroundtruthTimeStamp: 58
> 
> EllipsoidSLAM Project 2019, Beihang University.
> Input Sensor: RGB-D
> 
> Camera Parameters:
> 
> * fx: 535.4
> * fy: 539.2
> * cx: 320.1
> * cy: 247.6
> * k1: 0
> * k2: 0
> * p1: 0
> * p2: 0
> * fps: 30
> * rows: 480
> * cols: 640
> * Scale: 5000
> 
> * Open Symmetry Estimation.
> * Open Single-Frame Ellipsoid Estimation.
> * Open Groundplane Estimation
> 
> Press [ENTER] to continue ...
> 
> --------> New Frame : 0 Timestamp: 1341841278.842700
> [Frame.cpp] bboxMap :
> 0 175 24 560 397 28 0.42 0
> 
> * Estimate Ground Plane Succeeds: -0.0342327 0.00459375   0.999436  -0.103871
> * Add supporting plane to Ellipsoid Extractor.
> * Set groundplane param to optimizer.
>   -- Optimization parameters :
>   [ Using Ground Plane: -0.0342327 0.00459375   0.999436  -0.103871 ]
> * Gravity Prior : Open.
> * Scale_3dedge: 10000
> * Scale_GravityPrior: 100
>   -- GRAPH INFORMATION :
> * Object Num : 1
> * Vertices: 2
> * 2d Edges [Valid/Invalid] : 0 [0/0]
> * 3d Edges : 1
> * Gravity edges: 1
> 
> -> 1/58
> 
> Press [ENTER] to continue ...
> 
> --------> New Frame : 1 Timestamp: 1341841279.510700
> [Frame.cpp] bboxMap :
> 0 201 40 542 426 28 0.32 0
> 
> terminate called after throwing an instance of 'std::bad_alloc'
> what(): std::bad_alloc
> Aborted (core dumped)
> 
> Thanks for your help~

Hi, did you solved the issue? I met the same situation.
