### ISSUE TITLE
How did you calculate shape/localization error?

### ISSUE THREAD

**Issue by joshi-bharat** [XunshanMan/Object-oriented-SLAM#2]
This is not an error.
But I wanted to know how did you calculate localization and shape error. Is there a ground truth for that?
Did you have access to Quadric SLAM code for comparison?

**Comment by XunshanMan** [comment]
Hi, did you mean the ground truth of the objects? 
We annotated the objects manually using the point cloud to get the ground truth. The tool is like this one (https://github.com/XunshanMan/semantic-data-association-tool). However it's hard to use currently, we are planning to make it more user-friendly, and also release further experiment datasets after our paper is accepted.
For QuadricSLAM, its code has not been released publicly, so we reproduced by ourselves according to the paper.
I hope it helps.

**Comment by joshi-bharat** [comment]
@XunshanMan thank you very much. It certainly helped.

Is it possible that you share the QuadricSLAM code? If it's not possible I totally understand. I wanted to check if I can work with some custom datasets.
Thanks for the great work anyways.

**Comment by XunshanMan** [comment]
@joshi-bharat I think it'll take some time because of the recent events and influenced schedule. I'll share it on the github after I clean it up. :)

**Comment by joshi-bharat** [comment]
Thank you. I am closing this issue now.
